refresh_seconds: 3
carry_stale_days: 540
stocks:
- symbol: '600519'
  name: 贵州茅台
  exchange: SH
- symbol: 000858
  name: 五粮液
  exchange: SZ
- symbol: '600036'
  name: 招商银行
  exchange: SH
  expected_payments_per_year: 2
- symbol: '601398'
  name: 工商银行
  exchange: SH
- symbol: '600900'
  name: 长江电力
  exchange: SH
- symbol: '000651'
  name: 格力电器
  exchange: SZ
- symbol: '601318'
  name: 中国平安
  exchange: SH
- symbol: '300750'
  name: 宁德时代
  exchange: SZ
